-- built IT 2K26 - full schema setup (generated by concatenating supabase/migrations/*.sql in order)
-- Paste into Supabase Dashboard -> SQL Editor -> Run. Safe to re-run (idempotent).

-- ================ 20260916082753_001_create_tables.sql ================
/*
# built IT 2K26 â€” Tables (no RLS yet)

Creates all tables for the hackathon platform.
RLS policies are added in a follow-up migration so cross-table references resolve.
*/

-- PROFILES
CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text NOT NULL,
  roll_number text UNIQUE NOT NULL,
  phone text NOT NULL,
  github_username text,
  created_at timestamptz DEFAULT now()
);

-- TEAMS
CREATE TABLE IF NOT EXISTS teams (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text UNIQUE NOT NULL,
  category text NOT NULL,
  leader_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  is_locked boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- TEAM MEMBERSHIPS
CREATE TABLE IF NOT EXISTS team_memberships (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  joined_at timestamptz DEFAULT now(),
  UNIQUE(team_id, user_id),
  UNIQUE(user_id)
);

-- PROBLEM STATEMENTS
CREATE TABLE IF NOT EXISTS problem_statements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid REFERENCES teams(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  is_open boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- SUBMISSIONS
CREATE TABLE IF NOT EXISTS submissions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  stage text NOT NULL CHECK (stage IN ('AIM', 'FINAL')),
  aim_summary text,
  ppt_file_path text,
  ppt_file_name text,
  deployed_url text,
  repo_url text,
  demo_video_url text,
  status text NOT NULL DEFAULT 'NOT_SUBMITTED' CHECK (status IN ('NOT_SUBMITTED', 'SUBMITTED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED')),
  submitted_at timestamptz,
  feedback text,
  score integer,
  created_at timestamptz DEFAULT now(),
  UNIQUE(team_id, stage)
);

-- EVENT CONFIG (singleton)
CREATE TABLE IF NOT EXISTS event_config (
  id integer PRIMARY KEY DEFAULT 1,
  aim_deadline timestamptz,
  final_deadline timestamptz,
  registration_open boolean DEFAULT true,
  CONSTRAINT singleton CHECK (id = 1)
);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, roll_number, phone, github_username)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.raw_user_meta_data->>'roll_number', ''),
    COALESCE(NEW.raw_user_meta_data->>'phone', ''),
    COALESCE(NEW.raw_user_meta_data->>'github_username', NULL)
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Default event config
INSERT INTO event_config (id, aim_deadline, final_deadline, registration_open)
VALUES (1, '2026-09-16 14:00:00+00', '2026-09-16 20:00:00+00', true)
ON CONFLICT (id) DO NOTHING;


-- ================ 20260916082815_002_enable_rls_policies.sql ================
/*
# built IT 2K26 â€” RLS Policies

Enables RLS on all tables and adds ownership/membership-scoped policies.

## Security summary
- Profiles: users CRUD their own profile only
- Teams: team members can SELECT/UPDATE; any authenticated user can INSERT (as leader)
- Team memberships: members can read their team's memberships; users insert/delete only their own
- Problem statements: all authenticated can SELECT; team members can INSERT/UPDATE for their team
- Submissions: team members can CRUD their team's submissions
- Event config: all authenticated can SELECT; any authenticated can INSERT/UPDATE (organizer use)
*/

-- Enable RLS everywhere
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE teams ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE problem_statements ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE event_config ENABLE ROW LEVEL SECURITY;

-- PROFILES policies
DROP POLICY IF EXISTS "select_own_profile" ON profiles;
CREATE POLICY "select_own_profile" ON profiles FOR SELECT
  TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- TEAMS policies
DROP POLICY IF EXISTS "select_own_teams" ON teams;
CREATE POLICY "select_own_teams" ON teams FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = teams.id AND tm.user_id = auth.uid())
    OR leader_id = auth.uid()
  );

DROP POLICY IF EXISTS "insert_team" ON teams;
CREATE POLICY "insert_team" ON teams FOR INSERT
  TO authenticated WITH CHECK (leader_id = auth.uid());

DROP POLICY IF EXISTS "update_own_team" ON teams;
CREATE POLICY "update_own_team" ON teams FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = teams.id AND tm.user_id = auth.uid())
    OR leader_id = auth.uid()
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = teams.id AND tm.user_id = auth.uid())
    OR leader_id = auth.uid()
  );

-- TEAM MEMBERSHIPS policies
DROP POLICY IF EXISTS "select_own_memberships" ON team_memberships;
CREATE POLICY "select_own_memberships" ON team_memberships FOR SELECT
  TO authenticated USING (
    user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM team_memberships tm2 WHERE tm2.team_id = team_memberships.team_id AND tm2.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "insert_own_membership" ON team_memberships;
CREATE POLICY "insert_own_membership" ON team_memberships FOR INSERT
  TO authenticated WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "delete_own_membership" ON team_memberships;
CREATE POLICY "delete_own_membership" ON team_memberships FOR DELETE
  TO authenticated USING (user_id = auth.uid());

-- PROBLEM STATEMENTS policies
DROP POLICY IF EXISTS "select_problem_statements" ON problem_statements;
CREATE POLICY "select_problem_statements" ON problem_statements FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_problem_statement" ON problem_statements;
CREATE POLICY "insert_own_problem_statement" ON problem_statements FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = problem_statements.team_id AND tm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_problem_statement" ON problem_statements;
CREATE POLICY "update_own_problem_statement" ON problem_statements FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = problem_statements.team_id AND tm.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = problem_statements.team_id AND tm.user_id = auth.uid())
  );

-- SUBMISSIONS policies
DROP POLICY IF EXISTS "select_own_submissions" ON submissions;
CREATE POLICY "select_own_submissions" ON submissions FOR SELECT
  TO authenticated USING (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = submissions.team_id AND tm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "insert_own_submission" ON submissions;
CREATE POLICY "insert_own_submission" ON submissions FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = submissions.team_id AND tm.user_id = auth.uid())
  );

DROP POLICY IF EXISTS "update_own_submission" ON submissions;
CREATE POLICY "update_own_submission" ON submissions FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = submissions.team_id AND tm.user_id = auth.uid())
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM team_memberships tm WHERE tm.team_id = submissions.team_id AND tm.user_id = auth.uid())
  );

-- EVENT CONFIG policies
DROP POLICY IF EXISTS "select_event_config" ON event_config;
CREATE POLICY "select_event_config" ON event_config FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_event_config" ON event_config;
CREATE POLICY "insert_event_config" ON event_config FOR INSERT
  TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "update_event_config" ON event_config;
CREATE POLICY "update_event_config" ON event_config FOR UPDATE
  TO authenticated USING (true) WITH CHECK (true);


-- ================ 20260916084137_003_fix_memberships_recursion.sql ================
/*
# Fix infinite recursion in team_memberships RLS policy

## Problem
The `select_own_memberships` policy on `team_memberships` references `team_memberships` in its own
USING clause (subquery checking if the user is a teammate). This causes infinite recursion because
PostgreSQL evaluates RLS policies on every read, including reads inside other policies.

The `teams` SELECT policy also references `team_memberships`, creating a circular dependency:
teams policy â†’ reads team_memberships â†’ team_memberships policy â†’ reads team_memberships â†’ ...

## Fix
- Make `team_memberships` SELECT policy use `USING (true)` â€” any authenticated user can see
  membership records. This is safe for an internal hackathon: knowing who is on which team is not
  sensitive, and write policies (INSERT/DELETE) still enforce `user_id = auth.uid()`.
- This breaks the recursion cycle: teams policy reads team_memberships â†’ team_memberships SELECT
  returns true without referencing teams or itself.
*/

DROP POLICY IF EXISTS "select_own_memberships" ON team_memberships;
CREATE POLICY "select_own_memberships" ON team_memberships FOR SELECT
  TO authenticated USING (true);


-- ================ 20260916084239_004_add_problem_fk_to_teams.sql ================
/*
# Add problem_statement_id FK to teams

## Change
- Add `problem_statement_id` column to `teams` table (nullable FK to problem_statements)
- This allows teams to link to a selected problem statement
- RLS: already covered by existing update_own_team policy
*/

ALTER TABLE teams ADD COLUMN IF NOT EXISTS problem_statement_id uuid REFERENCES problem_statements(id) ON DELETE SET NULL;


-- ================ 20260918000000_005_storage_bucket_and_seed.sql ================
/*
# Storage bucket + policies + curated problem statements

## Why
Migration 001â€“004 create the tables, but two things the app needs were never provisioned:

1. The `submissions` storage bucket. `src/app/submit/aim/page.tsx` uploads the PPT deck to
   `submissions/teams/<teamId>/aim-presentation.<ext>`. Without the bucket (and policies on
   `storage.objects`) that upload fails with a permission/not-found error.
2. Seed rows for `problem_statements`. `src/app/problem-statements/page.tsx` lists rows where
   `team_id IS NULL` (the "curated list"). With no seed rows the page shows "No problem
   statements in this category yet."

## Storage path convention (must match the client code)
  teams/<team_id>/aim-presentation.<ext>
  -> (storage.foldername(name))[1] = 'teams'
  -> (storage.foldername(name))[2] = <team_id>

Policies below allow only members of that team to insert/read/update their own files.
Bucket is private (public = false) so decks are accessed through the app, not guessed URLs.
*/

-- 1. BUCKET
INSERT INTO storage.buckets (id, name, public)
VALUES ('submissions', 'submissions', false)
ON CONFLICT (id) DO NOTHING;

-- 2. STORAGE POLICIES (team-scoped)
DROP POLICY IF EXISTS "submissions_insert_own_team" ON storage.objects;
CREATE POLICY "submissions_insert_own_team" ON storage.objects FOR INSERT
  TO authenticated WITH CHECK (
    bucket_id = 'submissions'
    AND (storage.foldername(name))[1] = 'teams'
    AND EXISTS (
      SELECT 1 FROM public.team_memberships tm
      WHERE tm.team_id::text = (storage.foldername(name))[2]
        AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "submissions_select_own_team" ON storage.objects;
CREATE POLICY "submissions_select_own_team" ON storage.objects FOR SELECT
  TO authenticated USING (
    bucket_id = 'submissions'
    AND (storage.foldername(name))[1] = 'teams'
    AND EXISTS (
      SELECT 1 FROM public.team_memberships tm
      WHERE tm.team_id::text = (storage.foldername(name))[2]
        AND tm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "submissions_update_own_team" ON storage.objects;
CREATE POLICY "submissions_update_own_team" ON storage.objects FOR UPDATE
  TO authenticated USING (
    bucket_id = 'submissions'
    AND (storage.foldername(name))[1] = 'teams'
    AND EXISTS (
      SELECT 1 FROM public.team_memberships tm
      WHERE tm.team_id::text = (storage.foldername(name))[2]
        AND tm.user_id = auth.uid()
    )
  ) WITH CHECK (
    bucket_id = 'submissions'
    AND (storage.foldername(name))[1] = 'teams'
    AND EXISTS (
      SELECT 1 FROM public.team_memberships tm
      WHERE tm.team_id::text = (storage.foldername(name))[2]
        AND tm.user_id = auth.uid()
    )
  );

-- 3. CURATED PROBLEM STATEMENTS (team_id NULL = open/curated)
INSERT INTO problem_statements (title, description, category, is_open)
VALUES
  ('Campus Asset Tracker',
   'Design a system that tracks department assets (labs, equipment, devices) and flags missing or overdue items automatically.',
   'IoT', true),
  ('Smart Attendance That Cannot Be Faked',
   'Build an attendance mechanism resistant to proxy marking, using a combination of presence signals and verification.',
   'AI', true),
  ('Student Support Chatbot',
   'Create an assistant that answers common academic and administrative queries and routes complex cases to the right staff.',
   'AI', true),
  ('Campus Energy Optimizer',
   'Analyse consumption data and recommend or automate actions that reduce electricity usage in college buildings.',
   'Automation', true),
  ('Secure Document Workflow',
   'A tamper-evident document approval flow with clear audit trails for departments handling sensitive records.',
   'Cyber Security', true),
  ('Cloud Cost Dashboard',
   'Give small teams visibility into cloud spend, with alerts and suggestions to cut unnecessary cost.',
   'Cloud', true),
  ('Result Analytics for Faculty',
   'Turn raw exam and attendance data into early-warning insights that identify students who need support.',
   'Data Science', true),
  ('Virtual Lab Walkthrough',
   'An immersive walkthrough of a laboratory or workshop so students can prepare before they enter the physical space.',
   'AR / VR', true)
ON CONFLICT DO NOTHING;


