'use client';

import { useState, useEffect, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import AuthGuard from '@/components/AuthGuard';
import { supabase } from '@/lib/supabase';
import {
  getMyTeam,
  getTeamByCode,
  createJoinRequest,
  getMyPendingJoinRequest,
  getEventConfig,
  respondToJoinRequest,
  type MyPendingRequest,
} from '@/lib/data';

function TeamJoinContent() {
  const router = useRouter();
  const [teamName, setTeamName] = useState('');
  const [teamCode, setTeamCode] = useState('');
  const [pending, setPending] = useState<MyPendingRequest | null>(null);
  const [maxTeamSize, setMaxTeamSize] = useState(4);
  const [error, setError] = useState<string | null>(null);
  const [info, setInfo] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [checking, setChecking] = useState(true);

  useEffect(() => {
    (async () => {
      const team = await getMyTeam();
      if (team) { router.push('/dashboard'); return; }
      const req = await getMyPendingJoinRequest();
      setPending(req);
      const cfg = await getEventConfig();
      if (cfg) setMaxTeamSize(cfg.max_team_size);
      setChecking(false);
    })();
  }, [router]);

  const handleCreate = async (ev: FormEvent) => {
    ev.preventDefault();
    setError(null);
    setInfo(null);
    setLoading(true);

    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { setError('Not authenticated'); setLoading(false); return; }

    // Team code (BIT-XXXXXX) is generated by the database trigger
    // assign_team_code(); the domain/problem selection happens later on the
    // Problem Statements page — only the leader can set those.
    const { data: team, error: teamError } = await supabase
      .from('teams')
      .insert({ name: teamName.trim(), leader_id: user.id })
      .select()
      .single();

    if (teamError) {
      setError(teamError.message);
      setLoading(false);
      return;
    }

    const { error: memberError } = await supabase
      .from('team_memberships')
      .insert({ team_id: team.id, user_id: user.id });

    if (memberError) {
      setError(memberError.message);
      setLoading(false);
      return;
    }

    setLoading(false);
    router.push('/dashboard');
  };

  const handleJoin = async (ev: FormEvent) => {
    ev.preventDefault();
    setError(null);
    setInfo(null);
    setLoading(true);

    const team = await getTeamByCode(teamCode);

    if (!team) {
      setError('No team found with that code.');
      setLoading(false);
      return;
    }

    if (team.is_locked) {
      setError('This team is locked and cannot accept new members.');
      setLoading(false);
      return;
    }

    const { error: requestError } = await createJoinRequest(team.id);
    if (requestError) {
      setError(requestError);
      setLoading(false);
      return;
    }

    const req = await getMyPendingJoinRequest();
    setPending(req);
    setInfo(`Request sent to "${team.name}". The team leader must approve it.`);
    setLoading(false);
  };

  const handleCancelRequest = async () => {
    if (!pending) return;
    setError(null);
    setLoading(true);
    const { error: cancelError } = await respondToJoinRequest(pending.id, 'cancel');
    setLoading(false);
    if (cancelError) { setError(cancelError); return; }
    setPending(null);
    setInfo('Request cancelled.');
  };

  if (checking) {
    return (
      <div className="page-loading">
        <div className="loading-bracket">&lt; / &gt;</div>
        <p className="eyebrow">Loading...</p>
      </div>
    );
  }

  return (
    <div className="team-page">
      <h1>Form your team</h1>
      <p className="subtitle">Create a new team (you become the leader) or ask to join an existing one with its team code.</p>

      {pending && (
        <div className="waiting-banner" style={{ marginBottom: '24px' }}>
          <span>
            Join request pending for <strong>{pending.team?.name ?? 'a team'}</strong>
            {pending.team?.team_code && <> (code <strong style={{ fontFamily: "'JetBrains Mono', monospace" }}>{pending.team.team_code}</strong>)</>}
            {' '}— waiting for the leader to approve.
          </span>
          <button className="btn-text" onClick={handleCancelRequest} disabled={loading}>Cancel request</button>
        </div>
      )}

      {info && <div className="submit-success" style={{ marginBottom: '24px' }}><p>{info}</p></div>}

      <div className="team-options">
        <div className="team-option-card">
          <h3>Create a team</h3>
          <p className="option-desc">Start a new team and become its leader. A shareable team code is generated automatically.</p>
          <form className="team-option-form" onSubmit={handleCreate}>
            <div className="form-group">
              <label className="form-label">Team name</label>
              <input
                className="form-input"
                type="text"
                value={teamName}
                onChange={e => setTeamName(e.target.value)}
                placeholder="The Innovators"
                required
              />
            </div>
            <button type="submit" className="btn-primary" disabled={loading} style={{ justifyContent: 'center' }}>
              {loading ? 'Creating...' : 'Create team'}
            </button>
          </form>
        </div>

        <div className="team-option-card">
          <h3>Join a team</h3>
          <p className="option-desc">Have a team code? Send a join request — the team leader approves it.</p>
          <form className="team-option-form" onSubmit={handleJoin}>
            <div className="form-group">
              <label className="form-label">Team code</label>
              <input
                className="form-input"
                type="text"
                value={teamCode}
                onChange={e => setTeamCode(e.target.value.toUpperCase())}
                placeholder="BIT-7K4P9X"
                style={{ fontFamily: "'JetBrains Mono', monospace", letterSpacing: '0.1em' }}
                required
              />
              <span className="form-hint">Ask your team leader for the code (with or without the BIT- prefix).</span>
            </div>
            <button type="submit" className="btn-secondary" disabled={loading || !!pending} style={{ justifyContent: 'center' }}>
              {loading ? 'Sending...' : pending ? 'Request already pending' : 'Request to join'}
            </button>
          </form>
        </div>
      </div>

      {error && <div className="auth-error-banner" style={{ marginTop: '24px' }}>{error}</div>}

      <p className="form-hint" style={{ marginTop: '24px' }}>Teams can have up to {maxTeamSize} members.</p>
    </div>
  );
}

export default function TeamJoinPage() {
  return (
    <AuthGuard>
      <TeamJoinContent />
    </AuthGuard>
  );
}
